### PR TITLE
CI scripts and component documentation

### LINKED ISSUE #105: Use ophyd documentation helpers to supplement documentation of devices
Pending: https://github.com/bluesky/ophyd/pull/914

### PR DESCRIPTION
**Pull request by klauer**
* Update CI to shared scripts
* Trial run of ophyd docs helpers (Closes #105)

Looks OK, but I'm still not thrilled with the overall process and number of warnings generated:

image

### CODE REVIEW

**Comment by klauer** [comment]
conda-build is failing on CI (I _think_ as some dependencies are only on on the pcds-tag conda channel).
Will have to move this back to draft

**Comment by klauer** [comment]
Merged in @ZLLentz 's overlapping changes from #114 - will this work any better?

**Comment by ZLLentz** [comment]
I spy a green checkmark

**Comment by klauer** [comment]
Yesss! 👏  Those releases you just did made this viable, I'd bet.

**Review by ZLLentz — APPROVED** [review]
LGTM!

**Pull request merged**
