### PR TITLE
BUG: fix issue where macro motor readback was not hinted

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Make the macromotor readbacks hinted

## Motivation and Context

Did not show up in the BEC LiveTable
https://jira.slac.stanford.edu/browse/LCLSECSD-1098

## How Has This Been Tested?

It has not been tested

## Where Has This Been Documented?

It has not been documented

### CODE REVIEW

**Comment by tangkong** [comment]
This looks right to me but I don't know why the CI can't find the package itself?

**Comment by ZLLentz** [comment]
This is a knock-on effect from the CI here pushing itself to 3.10 and a deprecated import in the nearly defunct `pswalker`.
```
In [1]: from collections import Iterable
<ipython-input-1-c0513a1e6784>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
```

**Review by klauer — APPROVED** [review]
Seems fine to me. Shame about CI, but it's probably reasonable to ignore for just now

**Comment by ZLLentz** [comment]
I'm going to do a small edit just to make it use 3.9
When we make the leap to 3.10 we need to fix pswalker

**Comment by ZLLentz** [comment]
pyqt failure

considering briefly if there's a way to pin pyqt in ci helpers, else it will be pinned here too

**Comment by ZLLentz** [comment]
Will revisit when we're ready to update envs to 3.10 and/or pyqt 5.15 or higher

**Pull request merged**
