### PR TITLE
MNT: noarch, py3.7+

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- Update travis config to the shared configurations
- Make the package noarch and allow new python versions

## Motivation and Context

- related to https://github.com/pcdshub/pcds-envs/issues/87

## How Has This Been Tested?

- Hopefully the CI passes

### CODE REVIEW

**Comment by klauer** [comment]
Partial duplicate of #106, but can rebase that one on top of this should it actually pass.

**Comment by ZLLentz** [comment]
Ah shoot, I forgot to check existing PRs

**Comment by ZLLentz** [comment]
Well the actual unit tests don't pass, so I guess I'll look into that first. Not sure why it's failing like this only now and not in the last environment tag.

**Comment by klauer** [comment]
It's a bit bizarre - I don't recall seeing this:

pswalker sim on-import seems to do something strange:
```
RuntimeError: The success state of a status object cannot be changed by setting its `success` attribute directly. Call `set_finished()` or `set_exception(exc)`.
```

**Comment by ZLLentz** [comment]
conda picked an older version for some reason :shrug:

**Comment by ZLLentz** [comment]
python 3.7+ tests will not pass until pswalker is tagged, I'll go do a tagging run right now

**Pull request merged**
